### ISSUE TITLE
插件启动报错

### ISSUE THREAD

**Issue by chrisjian** [CppCXY/VSCode-EmmyLua-Unity#11]
电脑已经安装了.NetFramework了

```
PS C:\Users\Administrator\Downloads> .\DotNetVersions.exe -b
2.0.50727.4927 Service Pack 2
3.0.30729.4926 Service Pack 2
3.5.30729.4926 Service Pack 1
4.0.0.0
4.8.04084
```

报错log
```
[Warn  - 12:28:17] OmniSharp.Extensions.LanguageServer.Server.Configuration.DidChangeConfigurationProvider: No ConfigurationItems have been defined, configuration won't surface any configuration from the client! | 
[12:28:18 DBG] open solution ...
[12:28:22 DBG] [ʧ��] �����ļ���d:\performance_test_branch\client\Assembly-CSharp.csproj��ʱ Msbuild ʧ�ܣ�������Ϣ: C:\Program Files\dotnet\sdk\7.0.201\Microsoft.Common.CurrentVersion.targets: (4047, 7): ��GetFrameworkPath����������ʧ�ܡ�
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Shared.FrameworkLocationHelper.FindDotNetFrameworkPath(String currentRuntimePath, String prefix, DirectoryExists directoryExists, GetDirectories getDirectories, DotNetFrameworkArchitecture architecture)
   at Microsoft.Build.Shared.FrameworkLocationHelper.DotNetFrameworkSpec.GetPathToDotNetFramework(DotNetFrameworkArchitecture architecture)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by chrisjian** [comment]
查了下 好像是因为有其他java进程导致java启动不了

**Comment by CppCXY** [comment]
这个报错应该不影响使用

**Comment by CppCXY** [comment]
而且插件依赖的是dotnet core sdk,不是 dotnet framework 也就是dotnet 6.0以上

**Comment by chrisjian** [comment]
dotnet 6和7都安装了 打开unity工程里面的lua脚本之后 有个java的堆栈溢出

3�� 14, 2023 1:15:30 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
����: Unmatched cancel notification for request id 6
3�� 14, 2023 1:15:30 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
����: Unmatched cancel notification for request id 3
3�� 14, 2023 1:15:30 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
����: Unmatched cancel notification for request id 5
3�� 14, 2023 1:15:30 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
����: Unmatched cancel notification for request id 2
3�� 14, 2023 1:16:12 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
����: Internal error: java.lang.StackOverflowError
java.util.concurrent.CompletionException: java.lang.StackOverflowError
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.StackOverflowError
	at com.tang.vscode.extendApi.ExtendApiService.getNsMember(ExtendApiService.kt)
	at com.tang.vscode.extendApi.ExtendShortNameManager.processAllMembers(ExtendShortNameManager.kt:54)
	at com.tang.vscode.extendApi.ExtendShortNameManager.processAllMembers(ExtendShortNameManager.kt:62)
	at com.tang.vscode.extendApi.ExtendShortNameManager.processAllMembers(ExtendShortNameManager.kt:62)
	at com.tang.vscode.extendApi.ExtendShortNameManager.processAllMembers(ExtendShortNameManager.kt:62)
	at com.tang.vscode.extendApi.ExtendShortNameManager.processAllMembers(ExtendShortNameManager.kt:62)
	at com.tang.vscode.extendApi.ExtendShortNameManager.processAllMembers(ExtendShortNameManager.kt:62)
	at com.tang.vscode.extendApi.ExtendShortNameManager.processAllMembers(ExtendShortNameManager.kt:62)

**Comment by fgh23387736** [comment]
@chrisjian 问题解决没有，我也遇到了这个问题
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Shared.FrameworkLocationHelper.FindDotNetFrameworkPath(String currentRuntimePath, String prefix, DirectoryExists directoryExists, GetDirectories getDirectories, DotNetFrameworkArchitecture architecture)
   at Microsoft.Build.Shared.FrameworkLocationHelper.DotNetFrameworkSpec.GetPathToDotNetFramework(DotNetFrameworkArchitecture architecture)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
